language: ruby
rvm:
- ruby-head
deploy:
  provider: heroku
  app: sleepy-escarpment-99487
  api_key:
    secure: R5kmqoqU9I6e+qLANQNtwxtzMmRDJRhe7y+f+PTvkPoTEMj5vTAF4d5/GjiWt9NTsdU5AyzLyzlVIYTw4yycPxdX3NWZswTI/jzK92DQr5Urq0wbZcfXVvWwWbMQJw9ye8rtqjriJuVfowBYIxCyUajfTVHCwh7SBlExwgtWLZXeyW1g5D29+0WlxU35LU6uCeVt9YSRujSTi+6eQgCRwZw3VDGkPlBZv8OEjeR7TFOFREQO38PMb9wQ7WyHFJ5TY+3Q8/JNH1mFS8AXJ8zuaXTcQb0Jg/4Zbr+LNzWt9wYWgs++Si65+UCXMDHO8MRPDWH2XWkoB0hjKCIA9WLcNaxhM3zKcHVoolUs6lAvScIj4pgFaR5nufe3xr3u4c9gGIVvaU02oSCuYX3X9irC51gozlYghEAyxHDLuxOwds1kIkwoPxznznaWKJZQdv0OXpwLLox3Eff+75TWDwwTli4RQQRTu8HE/eLEzNg31KDsCQmNRmrFibJZfrzi/wrpZDf9G1xl65y1MoY6Kf5zSg7YvRfoYlhMf3IGC0ZW8dgQSQ4JfhNn9QxFizlhmuvAb5/vZGgduy289YgirtnweUPXEZiLWNU08qH6cWgOwTI6QaDOg384yjBKL708bhKZFWAKKMurU7YyvJGG6kZd+DxN1FsRxucjhRTseSGMgpY=
